services:
  backend:
    build: .
    ports:
      - "3701:3701"
    depends_on:
      - db
      - redis

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: ambassador
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - node_ambassador_dbdata:/var/lib/mysql
    ports:
      - "7080:3306"

  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  node_ambassador_dbdata:
