services:
  backend:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: users
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - node_users_dbdata:/var/lib/mysql
    ports:
      - "7082:3306"

volumes:
  node_users_dbdata:
