services:
  backend:
    build: .
    ports:
      - "3700:3700"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: users
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - node_users_dbdata:/var/lib/mysql
    ports:
      - "7082:3306"
    command: --bind-address=0.0.0.0

volumes:
  node_users_dbdata:
